### ISSUE TITLE
[BUG][NOWEB] - SCAN_QR_CODE WhatsApp Notification Issue

### ISSUE THREAD

**Issue by OrionEnes** [allburov/whatsapp-http-api#648] opened 2024-11-21 17:55 UTC
![Screenshot_16](https://github.com/user-attachments/assets/803f1618-401f-4aa5-9bf4-b052600428c4)
Hello,
We are using NOWEB, and when we create SCAN_QR_CODE, the WhatsApp notification often doesn't appear, causing users to have issues linking their numbers. Could you assist us with this problem?

**Comment by devlikepro** [comment] 2024-11-22 08:59
Hi! What version do you use? You can check it on Dashboard

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment] 2024-11-22 09:00
Does Copy Code work in your workflow? I remember WA apps doesn't allow to paste the code :thinking: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment] 2024-11-22 09:07
Could you try it on Dashboard? Also a suggestion - there's a manual flow if you don't get a notification, just remember to put this
![image](https://github.com/user-attachments/assets/32ad296b-342c-4a4e-a472-7af504db826d)

Tested it with latest `2024.11.5` + **Android** **latest** **WhatsApp** - it works

1. Does the flow work at all when you attach it manually via steps on Dashboard? 
2. Do you connect regular or Business account?
3. Could you test it on the latest WAHA + app?

I'll close the issue, feel free to add the details, we'll reopen if found the root cause !


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Closed as completed by devlikepro** 2024-11-22 09:07 UTC
Labels: bug, engine:NOWEB

**Comment by OrionEnes** [comment] 2024-11-22 09:45
We are using version 2024.11.3.
There are no issues with copying and pasting the code; it works fine.
However, when the code is generated by WAHA, no notification is received on WhatsApp.
Since our users generate the code themselves, they prefer not to do it manually.
