### ISSUE TITLE
Stuck on STARTING 

### ISSUE THREAD

**Issue by gr8tushar** [allburov/whatsapp-http-api#187] opened 2023-08-25 13:08 UTC
Hi,
After creating few sessions, when I am creating a new session it is stuck on "STARTING" state. It is not moving to the "SCAN_QR_CODE". 

Tried, restarting the docker. All the sessions are stuck in STARTING state. 

Here are the details / logs of the docker. 

I am using the following version:
`{ "version": "2023.8.23", "tier": "PLUS", "browser": "/usr/bin/chromium" }`

I was checking the logs and found this. Could be helpful in debugging.
`whatsapp-http-api-plus    | (node:34) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit whatsapp-http-api-plus    | (Use node --trace-warnings ... to show where the warning was created) whatsapp-http-api-plus    | (node:34) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit whatsapp-http-api-plus    | (node:34) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit whatsapp-http-api-plus    | (node:34) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit`

Thanks,
Tushar

**Comment by allburov** [comment] 2023-08-25 13:28
@gr8tushar could you try to remove `.sessions` directory and try again?
The emmiter warnings shouldn't affect it, may be there's some other logs available?

**Comment by gr8tushar** [comment] 2023-08-25 15:05
Hi @allburov - I removed the .sessions directory and restarted the process and everything worked fine.

To figure out the root cause, this is what I tried. This may be of some help to you.

USE CASE :1

- Started creating sessions quickly.
- The status of all of them became STARTING
- For about first 10, the status changed to SCAN_QR_CODE
- Created another 5
- Status of last three sessions was still STARTING
- Looked at the server, using top. 75 MB free memory
- Nothing changed in 15 minutes
- Abruptly restarted the server (shutdown -r). 
- Server started. All the sessions are in STARTING mode.

I checked the logs are saw that all the sessions are restored asynchronously. If they are restored synchronously, some of them might start.

Will try couple of things and update you.

Best,
Tushar

**Comment by allburov** [comment] 2023-08-29 10:12
>75 MB free memory

Could you try to increase the memory on 2GB (and may be CPU if it's 2 to set them to 4) and try it again? It could be performance issue

**Comment by allburov** [comment] 2023-08-29 10:14
The last time we've tested it 10 session require about 2.7 CPU and 1.5 GB of memory https://waha.devlike.pro/docs/overview/faq/#how-much-cpu-and-memory-does-whatsapp-http-api-consume

It might change since then, because there's a lot of changes made in WAHA, engines and WhatsApp itself, so you should try to adjust it for your case

**Comment by Devanagaraj** [comment] 2023-08-29 15:52
I am facing same issue on 

>  "version": "2023.7.16",
>   "tier": "PLUS",

server have 5GB of free memory and more than enough of CPU 

Steps to reproduce:
1. Started a session from the swagger panel
2. Status of that session updated to SCAN_QR_CODE
3. I scanned the code and checked screenshot of that session after 5 second and it have successfully logged in on web engine.
4. checked /Sessions  endpoint and the status of the session remained as SCAN_QR_CODE even after 5 minute.

Tried 5 times with different session name but Status of session is not updating...

**Comment by allburov** [comment] 2023-08-30 00:51
@Devanagaraj it's not the same issue, you have the different status. Scan QR has been fixed in latest version
https://github.com/devlikeapro/whatsapp-http-api/issues?q=is%3Aissue+is%3Aclosed

**Comment by allburov** [comment] 2023-09-03 10:46
@gr8tushar hi! Any updates after the above suggestion about memory?

**Comment by dv336699** [comment] 2023-09-05 00:11
guys, just wanted to offer a bit of advice, I was using a VPS to run the container and was having all sort of issues, after moving to a dedicated server with 8 core and 32GB everything has started to work as expected

**Comment by allburov** [comment] 2023-09-05 02:47
@dv336699 thank you for the feedback! 
@gr8tushar let us know if increasing CPU and Memory didn't help in your case, we'll look at this futher!

**Closed as completed by allburov** 2023-09-05 02:47 UTC
Labels: bug, engine:WEBJS

**Comment by Devanagaraj** [comment] 2023-09-07 16:07
I still have the issue on new version
